### ISSUE TITLE
crc32_combine

### ISSUE THREAD

**Issue by abalib** [antonblanchard/crc32-vpmsum#10]
How would I go about implementing the crc32_combine function?  Any pointers in your implementation?

https://github.com/madler/zlib/blob/master/crc32.c#L372
```local uLong crc32_combine_(crc1, crc2, len2)```

The combination problem is this:  given the existing crc32 checksums for two separate data buffers buf1 and buf2, what is the crc32() of the concatenated buf1+buf2?

Speed is not a concern here: two 32 bit ints combining in to one 32b int. The polynom math is difficult.

**Comment by grooverdan** [comment]
Looks like you just need to xor the two results like: https://stackoverflow.com/questions/6491834/is-it-possible-to-do-crc-32-calculation-in-splits

so: crc32(crc1, len1) xor crc32(crc2, len2)

**Comment by abalib** [comment]
Thanks for the pointer.  I will give it a try.  I didn't think it would be that simple given the complexity of crc32_combine() in zlib.

**Comment by grooverdan** [comment]
a better reference is probably https://en.wikipedia.org/wiki/Cyclic_redundancy_check#Data_integrity - third aspect - linear function. If that doesn't work for some reason let us know.

**Comment by abalib** [comment]
crc32 apparently is not additive such as crc1 xor crc2
Here is a more authoritative explanation. 
https://groups.google.com/d/msg/comp.compression/SHyr5bp5rtc/PP5-pmv9-9sJ
